platform :ios do
  lane :dev_build do
    match(type: "development")
    gym(
      scheme: "iOSSampleApp",
      export_method: "development"
    )
    sh("mkdir -p output && mv *.ipa output/")
  end
end
